name: "Use SurrealDB in GitHub Actions"
description: "Start a SurrealDB Server"

branding:
  icon: "database"
  color: "purple"

inputs:
  surrealdb-version:
    description: "SurrealDB version, default is latest"
    required: false
    default: "latest"
  surrealdb-port:
    description: "SurrealDB port, default is 8000"
    required: false
    default: 8000
  surrealdb-user:
    description: "SurrealDB root username, default is root"
    required: false
    default: "root"
  surrealdb-password:
    description: "SurrealDB root password, default is root"
    required: false
    default: "root"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.surrealdb-version }}
    - ${{ inputs.surrealdb-port }}
    - ${{ inputs.surrealdb-user }}
    - ${{ inputs.surrealdb-password }}
