name: Run Action

on:
  workflow_dispatch:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  schedule:
    - cron: "0 0 * * *"

jobs:
  surrealdb-action:
    runs-on: ubuntu-latest

    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Action
        uses: ./

      - name: Execute SurrealQL
        run: docker exec surrealdb /surreal version --endpoint http://localhost:8000
