name: Run Action

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  schedule:
    - cron: "0 0 * * *"

jobs:
  surrealdb-action:
    runs-on: ubuntu-latest

    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Action
        uses: ./
